
lingdata_config_path: cognate_lingdata_config.json
outdir: data/results_cognate/

software:
  raxml-ng:
    command: ./bin/raxml-ng
    threads: auto 
  pythia:
    command: pythia
    predictor: predictors/latest.pckl
