
lingdata_config_path: cognate_lingdata_config.json
outdir: data/results_cognate_single_noforce/

software:
  raxml-ng:
    command: ./bin/raxml-ng-single-noforce
    threads: auto
  pythia:
    command: pythia
    predictor: predictors/latest.pckl
